### ISSUE TITLE
Лишний слой при нарезке в FULL

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-Slicer#28]
При нарезке появляется лишний слой, если деталь отодвинуть от основания на 0.1 мм
![Лишний слой 1](https://user-images.githubusercontent.com/72873347/102864866-4fafef00-444e-11eb-9210-751781de28b2.PNG)
![Лишний слой 2](https://user-images.githubusercontent.com/72873347/102864869-50e11c00-444e-11eb-9182-068cec8d6c5e.PNG)

**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by frylock34** [comment]
Добавь конфигурацию глайсера и поделенную модель (находятся в папке Temp)

**Comment by ShvetsAA** [comment]
> Добавь конфигурацию глайсера и поделенную модель (находятся в папке Temp)

Файлы в #32
