### ISSUE TITLE
Несовпадение высот сердечника и модели

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-Slicer#32]
Сердечник строится выше, чем габариты модели, либо наоборот, модель не достраивается до своих габаритов, а сердечник достраивается.
![Высота 1](https://user-images.githubusercontent.com/72873347/102882824-7418c500-4468-11eb-90b1-5d86d63808d5.PNG)
![Высота](https://user-images.githubusercontent.com/72873347/102882829-74b15b80-4468-11eb-95f4-b940b8db526d.PNG)
[Высота.zip](https://github.com/stereotech/STE-Slicer/files/5729499/default.zip)

**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by frylock34** [comment]
Из-за различных направлений укладки слоев визуализация не может корректно отобразить GCode, поэтому появляется такое несовпадение. Физически данное несовпадение отсутствует.
