### ISSUE TITLE
Не нарезается кольцо с выемками

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-Slicer#33]
Процесс нарезки либо очень длительный (больше нескольких часов) либо проблема в зависании на каком-либо шаге. Лог прикладываю.
[Тяжелая модель.zip](https://github.com/stereotech/STE-Slicer/files/5753437/default.zip)

**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by frylock34** [comment]
Проблема с моделью, у нее были продублированы грани
