### ISSUE TITLE
Всплывающая подсказка перекрывает поле ввода данных

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-Slicer#34]
Может сделать так, чтобы при начале ввода с клавиатуры, она исчезала? Ну или хотя бы сдвинуть ее положение к правому краю поля. А то не видно, что вводишь.
![Всплывающая подсказка](https://user-images.githubusercontent.com/72873347/104711542-f11f1d80-573a-11eb-8403-c2fbc7aa9da1.PNG)

**Application Version**

1.12.21
**Platform**

WIN 10
**Printer**

STE530H
**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by frylock34** [comment]
Достаточно убрать с нее курсор и она исчезает
