### ISSUE TITLE
Добавить настройку "Сгенерировать оснастку"

### ISSUE THREAD

**Issue by Avdartrom** [stereotech/STE-Slicer#48]
Идеальный вариант: загружаем модель для печати в режиме Spiral. Нажимаем галку "Сгенерировать оснастку". Результат - на стандартном основании в 6 мм печатается сначала оснастка (предусмотреть возможность использовать для этого второй экструдер), идеально оснастка с отверстиями и прорезями под фиксацию винтами.

Предусмотреть возможность печати на конических оснастках (программа max - в общем случае, на любых оснастках)

**Comment by frylock34** [comment]
https://tracker.yandex.ru/SLICER-21
