### ISSUE TITLE
Объединение мелких разрозненных цилиндрических поддержек

### ISSUE THREAD

**Issue by ITorubarov** [stereotech/STE-Slicer#61]
Проблема: если нависающая часть модели не сплошная, а какая-нибудь фрагментарно-периодическая (как у решётки нейлонового фильтра), то и цилиндрические поддержки печатаются кусочками (рисунок прилагается). Время печати от этого растягивается, грязи обычно становится больше, и выколупывать эти кусочки - просто наказание.
![1](https://user-images.githubusercontent.com/73332725/141744371-9a8ebf96-d37e-4a56-9ce1-8cb4a0496cc9.jpg)

Решение: объединить мелкие поддержки в один большой и длинный зигзаг, который можно выдирать за один приём.

Можно ли сделать так, чтобы маленькие пустые области между поддержками (меньше некоторой заданной площади, скажем) заполнялись теми же поддержками и рисовались одним зигзагом?

**Comment by frylock34** [comment]
передам в Glicer

**Comment by frylock34** [comment]
https://tracker.yandex.ru/SLICER-18
