### ISSUE TITLE
Не строит поддержки в сердечнике

### ISSUE THREAD

**Issue by Stereotech-workshop** [stereotech/STE-Slicer#69]
https://user-images.githubusercontent.com/96297212/146549434-156c1cd8-74f3-4714-8e7f-b6ed66bc95fc.mp4

**Comment by frylock34** [comment]
В данном случае необходимо получать меш из разности сердечника и цилиндр и задавать ему печататься как поддержка

**Comment by frylock34** [comment]
![image](https://user-images.githubusercontent.com/16722747/147100114-0f129b75-2bbe-4e2f-8fb5-500c6f8cb2a3.png)
![Снимок экрана 2021-12-22 161719](https://user-images.githubusercontent.com/16722747/147100181-dd68b5ac-6d60-43b9-bd3d-399aabf81099.png)
