### ISSUE TITLE
Не нарезает модель в Spiral Full

### ISSUE THREAD

**Issue by Stereotech-workshop** [stereotech/STE-Slicer#73]
https://user-images.githubusercontent.com/96297212/146886107-341f3916-8aca-4bae-a673-d0c0e9e57a59.mp4
Z:\Студия 3D печати\Портфолио 3D печать\Печень и височная кость

Модель bp_FJ3281_BP12118_FMA52739_Left_temporal_bone_fixed.stl

**Comment by frylock34** [comment]
@Stereotech-workshop просьба приложить проект

**Comment by Stereotech-workshop** [comment]
Z:\Студия 3D печати\Портфолио 3D печать\Печень и височная кость

3mf проект сохранен

**Comment by frylock34** [comment]
![image](https://user-images.githubusercontent.com/16722747/146890254-dc7b1258-9c65-45c3-8947-c36b819ca1d9.png)

Не воспроизводится, возможно проблема у конкретного ПК или версии слайсера. На этой неделе будет собрана новая версия
