### ISSUE TITLE
Дополнение: Продумать автоматическое управление вентилятором обдува камеры

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-Slicer#76]
Не очень удобно на всех принтерах при серийной печати каждый раз включать обдув камеры вручную (в 95% случаев пользоваться им не будут).
Хорошо, если бы была такая настройка в слайсере. А если бы была зависимость от выбранного пластика в слайсере - было бы вообще замечательно (чтобы случайно не включали обдув на высокотемпературных пластиках, если они терпеть не могут обдув)

**Comment by frylock34** [comment]
Такое провернуть можно, нужна информация о величине обдува камеры для разных материалов

**Comment by ShvetsAA** [comment]
Для начала хватит ручной настройки 0-100% а-ля "обдув модели". Не брать значения обдува модели, а добавить второй, независимый орган управления в слайсере, но с тем же функционалом

**Comment by frylock34** [comment]
https://tracker.yandex.ru/SLICER-10
