### ISSUE TITLE
Доработка настройки перекрытия для плоской и цилиндрической части (full-режим) (Slicer 0-4-3)

### ISSUE THREAD

**Issue by ITorubarov** [stereotech/STE-Slicer#78]
Базовая задача #60 

Перекрытие работает ожидаемым образом. Если в full-режиме печатается монолитная модель, в текущем виде настройка отработает всё как надо.
Если модель имеет стаканообразную форму, при настройке перекрытия в 3D-часть попадают лишние части модели (кроме части дна - ещё вертикальные стойки, которые целиком должны печататься в spiral-е на боковой поверхности оправки).

![перекрытие](https://user-images.githubusercontent.com/73332725/147451925-3f00649a-d8cb-40bf-b72e-f4c3c3ba07f0.jpg)

![перекрытие 2](https://user-images.githubusercontent.com/73332725/147453102-d6017f85-4118-4bf0-8c68-c37f8086ba58.jpg)

Надо как-то избавиться от лишних кусков в 3D части.
Можно ли для full-режима сделать опциональную возможность воткнуть вспомогательную плоскость на произвольной высоте Z в модели и печатать сердечник не от "стола" (Z=0), а от этой вспомогательной плоскости?
Может быть, это сразу решит и проблему, которая описана в задаче #72 ? Про исчезающий сердечник при отрыве от Z0.

**Comment by ITorubarov** [comment]
![Без имени](https://user-images.githubusercontent.com/73332725/147458791-01040e7a-cff3-4c77-bdf6-a019044a0e6a.jpg)

Печать сердечника: всё, что выше доп. плоскости попало в область (Base Diameter + Overlap).
Всё, что ниже плоскости - на этом этапе игнорируется.

Печать цилиндрической части: как обычно.

**Comment by ITorubarov** [comment]
![4](https://user-images.githubusercontent.com/73332725/147461699-3525c16b-abd6-44f1-875d-2f52ac882d8a.jpg)
![4 — копия](https://user-images.githubusercontent.com/73332725/147461704-80ea8c7b-d275-45aa-99ae-681b834f5db2.jpg)

Слушай, по сути, если уронить модель дном на Z0, всё и так нормально работает

**Comment by frylock34** [comment]
Только если центрироваться на дальнем от патрона положении

**Comment by frylock34** [comment]
> ![4](https://user-images.githubusercontent.com/73332725/147461699-3525c16b-abd6-44f1-875d-2f52ac882d8a.jpg)
> ![4 — копия](https://user-images.githubusercontent.com/73332725/147461704-80ea8c7b-d275-45aa-99ae-681b834f5db2.jpg)
> 
> Слушай, по сути, если уронить модель дном на Z0, всё и так работает, как я хотел.
> Это можно считать допустимым, если цилиндрическая часть модели будет нарезаться изподстольным образом?

Только если центрироваться на дальнем от патрона положении

**Comment by ITorubarov** [comment]
> > Слушай, по сути, если уронить модель дном на Z0, всё и так работает, как я хотел.
> > Это можно считать допустимым, если цилиндрическая часть модели будет нарезаться изподстольным образом?
> 
> Только если центрироваться на дальнем от патрона положении

Ну, это понятно.
В принципе, на конце оправки даже удобнее зануляться, чем в начале, не нужно отступ высчитывать.

**Comment by ITorubarov** [comment]
Попробую сегодня или завтра таким макаром нарезать и запустить печать. Если принтер никуда не ушатается - задачу на этом закроем, наверное.

**Comment by frylock34** [comment]
https://tracker.yandex.ru/SLICER-12
