### ISSUE TITLE
Кнопка "Отправить отчет" едет на GitLab, а не на GitHub

### ISSUE THREAD

**Issue by ShvetsAA** [stereotech/STE-Slicer#80]
![image](https://user-images.githubusercontent.com/72873347/151543289-95fb4887-a917-42ec-b1d0-d16a68b0c79a.png)

![image](https://user-images.githubusercontent.com/72873347/151543244-3e9c4aab-c8ed-4a9c-96ae-ce1360b38457.png)

**Comment by frylock34** [comment]
https://tracker.yandex.ru/SLICER-8
